import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/context/UserContext";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { useContext } from "react";
import { UserContext } from "@/context/UserContext";
import Navbar from "./components/ui/Navbar";
import { FaGithub, FaInstagram, FaLinkedin } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Artoon",
  description: "Generated by Syed Shafin Ahmed",
  icons: {
    icon: "/art.png",
  },
};

export default function RootLayout({ children }) {
  console.log("API URL:", process.env.NEXT_PUBLIC_API_URL);

  return (
    <html lang="en" data-theme="light" className="max-w-7xl mx-auto">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          {/* navbar */}
          <Navbar></Navbar>
          {children}
          {/* footer */}
          <footer className="footer footer-horizontal text-base-200 footer-center bg-linear-to-bl from-blue-400 to-blue-600  rounded-xl p-10">
            <nav className="grid grid-flow-col gap-4">
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/">
                Home
              </Link>
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/aboutus">
                About Us
              </Link>
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/arts">
                Arts
              </Link>
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/blogs">
                Blogs
              </Link>
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/addarts">
                Add Arts
              </Link>
              <Link className="mr-3 font-medium text-xs md:text-sm" href="/managearts">
                Manage Arts
              </Link>
            </nav>
            <nav>
              <div className="grid grid-flow-col gap-4">
                <a href="https://github.com/syedshafinahmed">
                  <FaGithub size={30}></FaGithub>
                </a>
                <a href="https://www.instagram.com/__shafin__ahmed?igsh=mta0agj0odbqawv2yq==">
                  <FaInstagram size={30}></FaInstagram>
                </a>
                <a href="https://www.linkedin.com/in/syed-shafin-ahmed/">
                  <FaLinkedin size={30}></FaLinkedin>
                </a>
              </div>
            </nav>
            <aside>
              <p>
                Copyright © {new Date().getFullYear()} - All right reserved by{" "}
                <strong>Artoon</strong>
              </p>
            </aside>
          </footer>
        </UserProvider>
      </body>
    </html>
  );
}
